version: '3.8'
services:
  postgres:
    image: postgres
    container_name: movieflixcon
    environment:
      POSTGRES_DB: movieflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    restart: always
